// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2G6I_3fMhTxpKlUSURNKp8rpMf5q357k',
    appId: '1:843412077013:web:869f8007eb3d9bd0a5a55c',
    messagingSenderId: '843412077013',
    projectId: 'musicsocial-90b82',
    authDomain: 'musicsocial-90b82.firebaseapp.com',
    storageBucket: 'musicsocial-90b82.appspot.com',
    measurementId: 'G-RYTTY3B7QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh2hePTe9qUBROdWhDaGRHyy_xcKqS3HU',
    appId: '1:843412077013:android:24ef0cad26cb483aa5a55c',
    messagingSenderId: '843412077013',
    projectId: 'musicsocial-90b82',
    storageBucket: 'musicsocial-90b82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjhNQdNcE3HlThY6wDyjNnmocrJu0r4yY',
    appId: '1:843412077013:ios:7b30155e7e7cda29a5a55c',
    messagingSenderId: '843412077013',
    projectId: 'musicsocial-90b82',
    storageBucket: 'musicsocial-90b82.appspot.com',
    iosBundleId: 'com.example.musicsocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjhNQdNcE3HlThY6wDyjNnmocrJu0r4yY',
    appId: '1:843412077013:ios:0ed8fbb60795592ca5a55c',
    messagingSenderId: '843412077013',
    projectId: 'musicsocial-90b82',
    storageBucket: 'musicsocial-90b82.appspot.com',
    iosBundleId: 'com.example.musicsocial.RunnerTests',
  );
}
